-- unpivot of wb crops production (top 5 crops)
with cte as(
SELECT
  Dist_Name,
  AVG(RICE_PRODUCTION_1000_tons) AS AVG_RICE,
  AVG(WHEAT_PRODUCTION_1000_tons) AS AVG_WHEAT,
  AVG(KHARIF_SORGHUM_PRODUCTION_1000_tons) AS AVG_KHARIF_SORGHUM,
  AVG(RABI_SORGHUM_PRODUCTION_1000_tons) AS AVG_RABI_SORGHUM,
  AVG(SORGHUM_PRODUCTION_1000_tons) AS AVG_SORGHUM,
  AVG(PEARL_MILLET_PRODUCTION_1000_tons) AS AVG_PEARL_MILLET,
  AVG(MAIZE_PRODUCTION_1000_tons) AS AVG_MAIZE,
  AVG(FINGER_MILLET_PRODUCTION_1000_tons) AS AVG_FINGER_MILLET,
  AVG(BARLEY_PRODUCTION_1000_tons) AS AVG_BARLEY,
  AVG(CHICKPEA_PRODUCTION_1000_tons) AS AVG_CHICKPEA,
  AVG(PIGEONPEA_PRODUCTION_1000_tons) AS AVG_PIGEONPEA,
  AVG(MINOR_PULSES_PRODUCTION_1000_tons) AS AVG_MINOR_PULSES,
  AVG(GROUNDNUT_PRODUCTION_1000_tons) AS AVG_GROUNDNUT,
  AVG(SESAMUM_PRODUCTION_1000_tons) AS AVG_SESAMUM,
  AVG(RAPESEED_AND_MUSTARD_PRODUCTION_1000_tons) AS AVG_RAPESEED_AND_MUSTARD,
  AVG(SAFFLOWER_PRODUCTION_1000_tons) AS AVG_SAFFLOWER,
  AVG(CASTOR_PRODUCTION_1000_tons) AS AVG_CASTOR,
  AVG(LINSEED_PRODUCTION_1000_tons) AS AVG_LINSEED,
  AVG(SUNFLOWER_PRODUCTION_1000_tons) AS AVG_SUNFLOWER,
  AVG(SOYABEAN_PRODUCTION_1000_tons) AS AVG_SOYABEAN,
  AVG(OILSEEDS_PRODUCTION_1000_tons) AS AVG_OILSEEDS,
  AVG(SUGARCANE_PRODUCTION_1000_tons) AS AVG_SUGARCANE,
  AVG(COTTON_PRODUCTION_1000_tons) AS AVG_COTTON
FROM [ICRISAT-District Level Data]
GROUP BY Dist_Name
)

SELECT 
top 5
  Crop,
  AVG(Production) AS AverageProduction
FROM cte
UNPIVOT (
  Production FOR Crop IN (
    AVG_RICE, AVG_WHEAT, AVG_KHARIF_SORGHUM, AVG_RABI_SORGHUM,
    AVG_SORGHUM, AVG_PEARL_MILLET, AVG_MAIZE, AVG_FINGER_MILLET, AVG_BARLEY,
    AVG_CHICKPEA, AVG_PIGEONPEA, AVG_MINOR_PULSES, AVG_GROUNDNUT, AVG_SESAMUM,
    AVG_RAPESEED_AND_MUSTARD, AVG_SAFFLOWER, AVG_CASTOR, AVG_LINSEED, AVG_SUNFLOWER,
    AVG_SOYABEAN, AVG_SUGARCANE, AVG_COTTON
  )
) AS unpivoted
GROUP BY Crop
order by AverageProduction desc;

-- unpivot of wb crops production (top 5 districts)
with cte as(
SELECT
  Dist_Name,
  AVG(RICE_PRODUCTION_1000_tons) AS AVG_RICE,
  AVG(WHEAT_PRODUCTION_1000_tons) AS AVG_WHEAT,
  AVG(KHARIF_SORGHUM_PRODUCTION_1000_tons) AS AVG_KHARIF_SORGHUM,
  AVG(RABI_SORGHUM_PRODUCTION_1000_tons) AS AVG_RABI_SORGHUM,
  AVG(SORGHUM_PRODUCTION_1000_tons) AS AVG_SORGHUM,
  AVG(PEARL_MILLET_PRODUCTION_1000_tons) AS AVG_PEARL_MILLET,
  AVG(MAIZE_PRODUCTION_1000_tons) AS AVG_MAIZE,
  AVG(FINGER_MILLET_PRODUCTION_1000_tons) AS AVG_FINGER_MILLET,
  AVG(BARLEY_PRODUCTION_1000_tons) AS AVG_BARLEY,
  AVG(CHICKPEA_PRODUCTION_1000_tons) AS AVG_CHICKPEA,
  AVG(PIGEONPEA_PRODUCTION_1000_tons) AS AVG_PIGEONPEA,
  AVG(MINOR_PULSES_PRODUCTION_1000_tons) AS AVG_MINOR_PULSES,
  AVG(GROUNDNUT_PRODUCTION_1000_tons) AS AVG_GROUNDNUT,
  AVG(SESAMUM_PRODUCTION_1000_tons) AS AVG_SESAMUM,
  AVG(RAPESEED_AND_MUSTARD_PRODUCTION_1000_tons) AS AVG_RAPESEED_AND_MUSTARD,
  AVG(SAFFLOWER_PRODUCTION_1000_tons) AS AVG_SAFFLOWER,
  AVG(CASTOR_PRODUCTION_1000_tons) AS AVG_CASTOR,
  AVG(LINSEED_PRODUCTION_1000_tons) AS AVG_LINSEED,
  AVG(SUNFLOWER_PRODUCTION_1000_tons) AS AVG_SUNFLOWER,
  AVG(SOYABEAN_PRODUCTION_1000_tons) AS AVG_SOYABEAN,
  AVG(OILSEEDS_PRODUCTION_1000_tons) AS AVG_OILSEEDS,
  AVG(SUGARCANE_PRODUCTION_1000_tons) AS AVG_SUGARCANE,
  AVG(COTTON_PRODUCTION_1000_tons) AS AVG_COTTON
FROM [ICRISAT-District Level Data]
GROUP BY Dist_Name
)

SELECT 
top 5
  Dist_Name,
  max(Crop) as print_purpose,
  AVG(Production) AS AverageProduction
FROM cte
UNPIVOT (
  Production FOR Crop IN (
    AVG_RICE, AVG_WHEAT,
    AVG_SORGHUM, AVG_PEARL_MILLET, AVG_MAIZE, AVG_FINGER_MILLET, AVG_BARLEY,
    AVG_CHICKPEA, AVG_PIGEONPEA, AVG_MINOR_PULSES, AVG_GROUNDNUT, AVG_SESAMUM,
    AVG_RAPESEED_AND_MUSTARD, AVG_SAFFLOWER, AVG_CASTOR, AVG_LINSEED, AVG_SUNFLOWER,
    AVG_SOYABEAN, AVG_SUGARCANE, AVG_COTTON
  )
) AS unpivoted
GROUP BY Dist_Name
order by AverageProduction desc;

-- unpivot of wb crops production (top 5 year)
with cte as(
SELECT
  year,
  Dist_Name,
  AVG(RICE_PRODUCTION_1000_tons) AS AVG_RICE,
  AVG(WHEAT_PRODUCTION_1000_tons) AS AVG_WHEAT,
  AVG(KHARIF_SORGHUM_PRODUCTION_1000_tons) AS AVG_KHARIF_SORGHUM,
  AVG(RABI_SORGHUM_PRODUCTION_1000_tons) AS AVG_RABI_SORGHUM,
  AVG(SORGHUM_PRODUCTION_1000_tons) AS AVG_SORGHUM,
  AVG(PEARL_MILLET_PRODUCTION_1000_tons) AS AVG_PEARL_MILLET,
  AVG(MAIZE_PRODUCTION_1000_tons) AS AVG_MAIZE,
  AVG(FINGER_MILLET_PRODUCTION_1000_tons) AS AVG_FINGER_MILLET,
  AVG(BARLEY_PRODUCTION_1000_tons) AS AVG_BARLEY,
  AVG(CHICKPEA_PRODUCTION_1000_tons) AS AVG_CHICKPEA,
  AVG(PIGEONPEA_PRODUCTION_1000_tons) AS AVG_PIGEONPEA,
  AVG(MINOR_PULSES_PRODUCTION_1000_tons) AS AVG_MINOR_PULSES,
  AVG(GROUNDNUT_PRODUCTION_1000_tons) AS AVG_GROUNDNUT,
  AVG(SESAMUM_PRODUCTION_1000_tons) AS AVG_SESAMUM,
  AVG(RAPESEED_AND_MUSTARD_PRODUCTION_1000_tons) AS AVG_RAPESEED_AND_MUSTARD,
  AVG(SAFFLOWER_PRODUCTION_1000_tons) AS AVG_SAFFLOWER,
  AVG(CASTOR_PRODUCTION_1000_tons) AS AVG_CASTOR,
  AVG(LINSEED_PRODUCTION_1000_tons) AS AVG_LINSEED,
  AVG(SUNFLOWER_PRODUCTION_1000_tons) AS AVG_SUNFLOWER,
  AVG(SOYABEAN_PRODUCTION_1000_tons) AS AVG_SOYABEAN,
  AVG(OILSEEDS_PRODUCTION_1000_tons) AS AVG_OILSEEDS,
  AVG(SUGARCANE_PRODUCTION_1000_tons) AS AVG_SUGARCANE,
  AVG(COTTON_PRODUCTION_1000_tons) AS AVG_COTTON
FROM [ICRISAT-District Level Data]
GROUP BY Dist_Name,Year
)

SELECT 
top 5
  YEAR,
  max(Crop) as print_purpose,
  AVG(Production) AS AverageProduction
FROM cte
UNPIVOT (
  Production FOR Crop IN (
    AVG_RICE, AVG_WHEAT,
    AVG_SORGHUM, AVG_PEARL_MILLET, AVG_MAIZE, AVG_FINGER_MILLET, AVG_BARLEY,
    AVG_CHICKPEA, AVG_PIGEONPEA, AVG_MINOR_PULSES, AVG_GROUNDNUT, AVG_SESAMUM,
    AVG_RAPESEED_AND_MUSTARD, AVG_SAFFLOWER, AVG_CASTOR, AVG_LINSEED, AVG_SUNFLOWER,
    AVG_SOYABEAN, AVG_SUGARCANE, AVG_COTTON
  )
) AS unpivoted
GROUP BY YEAR
order by AverageProduction desc;